version: 0.2

phases:
  install:
    commands:
      # Install dependencies if needed (like wget, curl, etc.)
      - echo Installing dependencies...
      - yum install -y wget

  pre_build:
    commands:
      - echo Pulling WAR file from S3...
      - sudo yum install awscli -y
      - aws s3 cp s3://alblogtestsagar/01-maven-web-app.war /opt

  post_build:
    commands:
      - echo Build and deployment complete.
